FORMAT: 1A

# POI manager

## POI Containers [/api.php/containers]
### List all POI Containers [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
            {
              "id": 1,
              "type": "document",
              "contentType": "text\/html",
              "pagetitle": "First container",
              "longtitle": "",
              "description": "",
              "alias": "",
              "link_attributes": "",
              "published": false,
              "pub_date": 0,
              "unpub_date": 0,
              "parent": 0,
              "isfolder": false,
              "introtext": "",
              "content": "",
              "richtext": true,
              "template": 1,
              "menuindex": 3,
              "searchable": true,
              "cacheable": true,
              "createdby": 1,
              "createdon": "2013-11-07 20:03:07",
              "editedby": 0,
              "editedon": 0,
              "deleted": false,
              "deletedon": 0,
              "deletedby": 0,
              "publishedon": 0,
              "publishedby": 0,
              "menutitle": "",
              "donthit": false,
              "privateweb": false,
              "privatemgr": false,
              "content_dispo": 0,
              "hidemenu": false,
              "class_key": "MarvinCategory",
              "context_key": "web",
              "content_type": 1,
              "uri": "",
              "uri_override": 0,
              "hide_children_in_tree": 0,
              "show_in_tree": 1,
              "properties": null,
              "icon": "",
              "color": "#0000FF",
              "category": "14"
            },
            {
              "id": 2,
              "type": "document",
              "contentType": "text\/html",
              "pagetitle": "Second container",
              "longtitle": "",
              "description": "",
              "alias": "",
              "link_attributes": "",
              "published": false,
              "pub_date": 0,
              "unpub_date": 0,
              "parent": 0,
              "isfolder": false,
              "introtext": "",
              "content": "",
              "richtext": true,
              "template": 1,
              "menuindex": 1,
              "searchable": true,
              "cacheable": true,
              "createdby": 1,
              "createdon": "2013-11-12 13:29:08",
              "editedby": 0,
              "editedon": 0,
              "deleted": false,
              "deletedon": 0,
              "deletedby": 0,
              "publishedon": 0,
              "publishedby": 0,
              "menutitle": "",
              "donthit": false,
              "privateweb": false,
              "privatemgr": false,
              "content_dispo": 0,
              "hidemenu": false,
              "class_key": "MarvinCategory",
              "context_key": "web",
              "content_type": 1,
              "uri": "",
              "uri_override": 0,
              "hide_children_in_tree": 0,
              "show_in_tree": 1,
              "properties": null,
              "icon": "",
              "color": "",
              "category": "15"
            }
          ]
        }

## POI Container [/api.php/containers/{id}]
A single POI Container object

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Container to perform action with. Has example value.

### Retrieve a Container [GET]
+ Response 200 (application/json)

        {
            "msg": "success",
            "data": {
                "id": 1,
                "icon": "",
                "color": "#0000FF",
                "category": 1,
                "type": "document",
                "contentType": "text/html",
                "pagetitle": "test category",
                "longtitle": "",
                "description": "",
                "alias": "",
                "link_attributes": "",
                "published": false,
                "pub_date": 0,
                "unpub_date": 0,
                "parent": 0,
                "isfolder": false,
                "introtext": "",
                "content": "",
                "richtext": true,
                "template": 1,
                "menuindex": 3,
                "searchable": true,
                "cacheable": true,
                "createdby": 1,
                "createdon": "2013-11-07 20:03:07",
                "editedby": 0,
                "editedon": 0,
                "deleted": false,
                "deletedon": 0,
                "deletedby": 0,
                "publishedon": 0,
                "publishedby": 0,
                "menutitle": "",
                "donthit": false,
                "privateweb": false,
                "privatemgr": false,
                "content_dispo": 0,
                "hidemenu": false,
                "class_key": "MarvinCategory",
                "context_key": "web",
                "content_type": 1,
                "uri": "",
                "uri_override": 0,
                "hide_children_in_tree": 0,
                "show_in_tree": 1,
                "properties": null
            }
        }

## POIs [/api.php/pois]
### List all POIs [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
		"id": "99400387404",
		"lon": "2.1909418",
		"lat": "41.436214",
		"distance": null,
		"category_id": 3,
		"district_id": 9,
		"image_id": 1,
		"contents": [{
			"title": "La pla\u00e7a d\u2019Orfila",
			"excerpt": "Punt de trobada dels ve\u00efns del barri, la pla\u00e7a d\u2019Orfila conserva l\u2019ess\u00e8ncia i la mem\u00f2ria de l\u2019antiga vila independent que va ser Sant Andreu de Palomar.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "99400118971",
		"lon": "2.2216976",
		"lat": "41.411034",
		"distance": null,
		"category_id": 3,
		"district_id": 10,
		"image_id": 2,
		"contents": [{
			"title": "El parc del F\u00f2rum",
			"excerpt": "El recinte projectat arran de mar per acollir el F\u00f2rum Universal de les Cultures 2004 \u00e9s avui dia un parc obert a tothom i on se celebren grans esdeveniments.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "92086011942",
		"lon": "2.1418977",
		"lat": "41.394073",
		"distance": null,
		"category_id": 2,
		"district_id": 5,
		"image_id": 3,
		"contents": [{
			"title": "El Tur\u00f3 Park",
			"excerpt": "Antic parc d\u2019atraccions transformat en pulm\u00f3 verd, el Tur\u00f3 Park \u00e9s un espai emblem\u00e0tic que inclou un recorregut po\u00e8tic.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "97042092100",
		"lon": "2.1306581",
		"lat": "41.41327",
		"distance": null,
		"category_id": 4,
		"district_id": 5,
		"image_id": 4,
		"contents": [{
			"title": "El CosmoCaixa",
			"excerpt": "Situat a la falda del Tibidabo, el CosmoCaixa ofereix activitats per a tothom i permet viure la ci\u00e8ncia a tocar de la m\u00e0.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "92086009457",
		"lon": "2.1297863",
		"lat": "41.38405",
		"distance": null,
		"category_id": 7,
		"district_id": 4,
		"image_id": 5,
		"contents": [{
			"title": "El Mercat de les Corts",
			"excerpt": "Amb mig segle d\u2019hist\u00f2ria i sempre vital, el Mercat de les Corts \u00e9s un punt essencial de trobada i comer\u00e7 dins el barri que li d\u00f3na nom.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "92086000123",
		"lon": "2.1584644",
		"lat": "41.36809",
		"distance": null,
		"category_id": 6,
		"district_id": 3,
		"image_id": 6,
		"contents": [{
			"title": "El Teatre Grec",
			"excerpt": "Dissenyat al pendent de la muntanya de Montju\u00efc, com si es tract\u00e9s d\u2019un amfiteatre cl\u00e0ssic, el Teatre Grec de Barcelona \u00e9s l\u2019emblema de la cultura esc\u00e8nica de Barcelona.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "92086008895",
		"lon": "2.1467245",
		"lat": "41.369118",
		"distance": null,
		"category_id": 3,
		"district_id": 3,
		"image_id": 7,
		"contents": [{
			"title": "El Poble Espanyol",
			"excerpt": "Un petit poble amb molts pobles a dins. Aix\u00ed \u00e9s el Poble Espanyol, concebut el 1929 per oferir una visi\u00f3 conjunta de les diverses comunitats de la pen\u00ednsula Ib\u00e8rica.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "92168175198",
		"lon": "2.1523776",
		"lat": "41.36197",
		"distance": null,
		"category_id": 5,
		"district_id": 3,
		"image_id": 8,
		"contents": [{
			"title": "El Palau Sant Jordi",
			"excerpt": "El colossal edifici del Palau Sant Jordi, constru\u00eft per als Jocs Ol\u00edmpics de Barcelona 1992, \u00e9s tot un s\u00edmbol de l\u2019esport, l\u2019oci i la diversi\u00f3 dels barcelonins.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "95275100026",
		"lon": "2.155663",
		"lat": "41.36471",
		"distance": null,
		"category_id": 8,
		"district_id": 3,
		"image_id": 9,
		"contents": [{
			"title": "L\u2019Estadi Ol\u00edmpic Llu\u00eds Companys",
			"excerpt": "L\u2019emblem\u00e0tic Estadi Ol\u00edmpic Llu\u00eds Companys ha acollit alguns dels moments m\u00e9s importants de la ciutat, com els Jocs Ol\u00edmpics de Barcelona 1992.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "99322140211",
		"lon": "2.149575",
		"lat": "41.371296",
		"distance": null,
		"category_id": 4,
		"district_id": 3,
		"image_id": 10,
		"contents": [{
			"title": "El CaixaForum",
			"excerpt": "Des que va obrir les portes a inicis del segle XXI, el CaixaForum s\u2019ha posicionat com un dels centres culturals de refer\u00e8ncia de la ciutat.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "99400267330",
		"lon": "2.149957",
		"lat": "41.376007",
		"distance": null,
		"category_id": 7,
		"district_id": 2,
		"image_id": 11,
		"contents": [{
			"title": "Les Arenes",
			"excerpt": "L\u2019antiga pla\u00e7a de toros de les Arenes, situada a la pla\u00e7a d'Espanya, es va transformar l\u2019any 2007 en un dels centres comercials m\u00e9s sorprenents de la ciutat.",
			"locales": {
				"code": "ca"
			}
		}]
	}, {
		"id": "92086011621",
		"lon": "2.159514",
		"lat": "41.396103",
		"distance": null,
		"category_id": 6,
		"district_id": 2,
		"image_id": 12,
		"contents": [{
			"title": "El Palau Robert",
			"excerpt": "A la cantonada del passeig de Gr\u00e0cia amb l\u2019avinguda Diagonal, el neocl\u00e0ssic Palau Robert \u00e9s un emblem\u00e0tic centre cultural que amaga un jard\u00ed preci\u00f3s obert a tothom.",
			"locales": {
				"code": "ca"
			}
		}
            ]
        }            

## POIs [/api.php/containers/{id}/pois]

+ Parameters
    + id (required, number, `15`) ... Numeric `id` of the Container to perform action with. Has example value.
    
### List all POIs under specific container [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 3,
                    "created": "2013-11-28 13:42:57",
                    "updated": "2014-01-14 15:35:35",
                    "updated_by": 1,
                    "deleted": 0,
                    "name": "Second location",
                    "alias": "second-location",
                    "lat": 50.757308959961,
                    "lng": 15.062255859375,
                    "zoom": 7,
                    "state": "new",
                    "type": 6,
                    "typeFields": {
                        "6": {
                            "name": "content",
                            "value": "this is a content"
                        }
                    }
                }
            ]
        }          

## POI [/api.php/pois/{id}]
A single POI object

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the POI to perform action with. Has example value.

### Retrieve the POI [GET]
+ Response 200 (application/json)

        {
            "msg": "success",
            "data": {
                "id": 1,
                "created": "2013-11-14 19:44:16",
                "updated": "2014-01-14 15:35:15",
                "updated_by": 1,
                "deleted": 0,
                "name": "First location",
                "alias": "first-location",
                "lat": 50.082759857178,
                "lng": 14.465103149414,
                "zoom": 12,
                "state": "new",
                "type": 1,
                "typeFields": {
                    "4": {
                        "name": "Author's name",
                        "value": "John Smith"
                    },
                    "3": {
                        "name": "Description",
                        "value": "this is a description"
                    },
                    "5": {
                        "name": "Author's email",
                        "value": "example@example.com"
                    }
                }
            }
        }

## POI Photos [/api.php/pois/{id}/photos]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the POI to perform action with. Has example value.

### List all Photos attached to specific POI [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 1,
                    "created": "2014-01-07 15:29:48",
                    "updated": 0,
                    "updated_by": 0,
                    "deleted": 0,
                    "name": "smith",
                    "description": "avatar picture",
                    "file": "smith.png",
                    "authors_name": "John Smith",
                    "authors_email": "example@example.com",
                    "location": 1
                }
            ]
        }

## POI Photo [/api.php/photos/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Photo to perform action with. Has example value.

### Retrieve specific Photo [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 1,
                    "created": "2014-01-07 15:29:48",
                    "updated": 0,
                    "updated_by": 0,
                    "deleted": 0,
                    "name": "smith",
                    "description": "avatar picture",
                    "file": "smith.png",
                    "authors_name": "John Smith",
                    "authors_email": "example@example.com",
                    "location": 1
                }
            ]
        }

## POI Comments [/api.php/pois/{id}/comments]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the POI to perform action with. Has example value.

### List all Comments attached to specific POI [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 1,
                    "created": "2013-11-20 15:07:41",
                    "updated": "2014-01-22 13:21:55",
                    "updated_by": 1,
                    "deleted": 0,
                    "text": "this is a first comment",
                    "authors_name": "John Smith",
                    "authors_email": "example@example.com",
                    "state": "approved",
                    "location": 1
                }
            ]
        }

## POI Comment [/api.php/comments/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Comment to perform action with. Has example value.

### Retrieve specific Comment [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 1,
                    "created": "2013-11-20 15:07:41",
                    "updated": "2014-01-22 13:21:55",
                    "updated_by": 1,
                    "deleted": 0,
                    "text": "this is a first comment",
                    "authors_name": "John Smith",
                    "authors_email": "example@example.com",
                    "state": "approved",
                    "location": 1
                }
            ]
        }

## POI Feedbacks [/api.php/pois/{id}/feedbacks]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the POI to perform action with. Has example value.

### List all Feedbacks attached to specific POI [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 1,
                    "created": "2013-11-16 14:06:43",
                    "updated": "2014-01-22 13:23:37",
                    "updated_by": 1,
                    "deleted": 0,
                    "text": "this is a first feedback",
                    "authors_name": "John Smith",
                    "authors_email": "example@example.com",
                    "state": "solved",
                    "location": 1
                },
                {
                    "id": 2,
                    "created": "2013-11-16 14:06:45",
                    "updated": "2013-11-20 15:07:41",
                    "updated_by": 1,
                    "deleted": 0,
                    "text": "This is a second feedback",
                    "authors_name": "John Smith",
                    "authors_email": "example@example.com",
                    "state": "in_progress",
                    "location": 1
                }
            ]
        }

## POI Feedback [/api.php/feedbacks/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Feedback to perform action with. Has example value.

### Retrieve specific Feedback [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 1,
                    "created": "2013-11-16 14:06:43",
                    "updated": "2014-01-22 13:23:37",
                    "updated_by": 1,
                    "deleted": 0,
                    "text": "this is a first feedback",
                    "authors_name": "John Smith",
                    "authors_email": "example@example.com",
                    "state": "solved",
                    "location": 1
                }
            ]
        }

## POI Types [/api.php/poitypes]
### List all POI Types [GET]
+ Response 200 (application/json)
        
        {
          "msg": "success",
          "data": [
            {
              "id": 1,
              "created": "2013-11-27 14:40:21",
              "updated": "2014-01-20 01:26:13",
              "updated_by": 1,
              "deleted": 0,
              "name": "Default",
              "description": "Default type",
              "default": 1
            },
            {
              "id": 2,
              "created": "2013-11-27 14:40:53",
              "updated": 0,
              "updated_by": 0,
              "deleted": "2013-11-27 14:45:46",
              "name": "Another type",
              "description": "This is just another type",
              "default": 0
            }
          ]
        }

## Fields for specific POI Type [/api.php/poitypes/{type}/fields]

+ Parameters
    + type (required, number, `1`) ... Numeric `id` of the POI Type to perform action with. Has example value.
    
### List all fields for specific POI Type [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 4,
                    "created": "2013-11-23 17:40:58",
                    "updated": "2013-11-23 18:14:37",
                    "updated_by": 1,
                    "deleted": 0,
                    "name": "Author's name",
                    "type": "textfield",
                    "default": "",
                    "required": 1,
                    "read_only": 0,
                    "position": 1,
                    "location_type": 1
                },
                {
                    "id": 3,
                    "created": "2013-11-23 17:40:48",
                    "updated": "2013-11-23 18:14:29",
                    "updated_by": 1,
                    "deleted": 0,
                    "name": "Description",
                    "type": "textarea",
                    "default": "",
                    "required": 0,
                    "read_only": 1,
                    "position": 3,
                    "location_type": 1
                },
                {
                    "id": 5,
                    "created": "2013-11-23 17:52:10",
                    "updated": "2013-11-23 18:05:26",
                    "updated_by": 1,
                    "deleted": 0,
                    "name": "Author's email",
                    "type": "textfield",
                    "default": "",
                    "required": 1,
                    "read_only": 0,
                    "position": 2,
                    "location_type": 1
                }
            ]
        }

## Field [/api.php/poitypes/{type}/fields/{id}]

+ Parameters
    + type (required, number, `1`) ... Numeric `id` of the POI Type to perform action with. Has example value.
    + id (required, number, `4`) ... Numeric `id` of the Field to perform action with. Has example value.
    
### List all fields for specific POI Type [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 4,
                    "created": "2013-11-23 17:40:58",
                    "updated": "2013-11-23 18:14:37",
                    "updated_by": 1,
                    "deleted": 0,
                    "name": "Author's name",
                    "type": "textfield",
                    "default": "",
                    "required": 1,
                    "read_only": 0,
                    "position": 1,
                    "location_type": 1
                }
            ]
        }

## Field [/api.php/fields/{id}]

+ Parameters
    + id (required, number, `4`) ... Numeric `id` of the Field to perform action with. Has example value.
    
### List all fields for specific POI Type [GET]
+ Response 200 (application/json)
        
        {
            "msg": "success",
            "data": [
                {
                    "id": 4,
                    "created": "2013-11-23 17:40:58",
                    "updated": "2013-11-23 18:14:37",
                    "updated_by": 1,
                    "deleted": 0,
                    "name": "Author's name",
                    "type": "textfield",
                    "default": "",
                    "required": 1,
                    "read_only": 0,
                    "position": 1,
                    "location_type": 1
                }
            ]
        }

